#!/bin/bash
set -e

CONFIG_FILE="/var/www/html/config.php"
CONFIG_DIR="/var/www/html/config"

generate_installation_id() {
    if [ -z "$INSTALLATION_ID" ]; then
        INSTALLATION_ID=$(openssl rand -hex 16)
        echo "Generated new Installation ID: $INSTALLATION_ID"
    fi
}

wait_for_db() {
    echo "Waiting for database to be ready..."
    max_tries=30
    count=0
    
    while [ $count -lt $max_tries ]; do
        if mysqladmin ping -h"$DB_HOST" -P"${DB_PORT:-3306}" -u"$DB_USER" -p"$DB_PASSWORD" --ssl=0 --silent 2>/dev/null; then
            echo "Database is ready!"
            return 0
        fi
        
        count=$((count + 1))
        echo "Database not ready yet... (attempt $count/$max_tries)"
        sleep 2
    done
    
    echo "ERROR: Database failed to become ready in time"
    return 1
}

check_database_initialized() {
    echo "Checking if database is initialized..."
    
    # Check if users table exists
    table_count=$(mysql -h"$DB_HOST" -P"${DB_PORT:-3306}" -u"$DB_USER" -p"$DB_PASSWORD" --ssl=0 -D"$DB_NAME" -sse "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '$DB_NAME';" 2>/dev/null || echo "0")
    
    if [ "$table_count" -eq "0" ]; then
        echo "Database is empty. Importing schema..."
        return 1
    else
        echo "Database already initialized ($table_count tables found)"
        return 0
    fi
}

initialize_database() {
    echo "Initializing ITFlow database schema..."
    
    if [ ! -f "/var/www/html/db.sql" ]; then
        echo "ERROR: db.sql not found!"
        return 1
    fi
    
    # Import database schema
    if mysql -h"$DB_HOST" -P"${DB_PORT:-3306}" -u"$DB_USER" -p"$DB_PASSWORD" --ssl=0 "$DB_NAME" < /var/www/html/db.sql 2>/dev/null; then
        echo "Database schema imported successfully!"
        return 0
    else
        echo "ERROR: Failed to import database schema"
        return 1
    fi
}

generate_config() {
    echo "Generating config.php from environment variables..."
    
    # Set defaults
    DB_HOST="${DB_HOST:-db}"
    DB_PORT="${DB_PORT:-3306}"
    DB_NAME="${DB_NAME:-itflow}"
    DB_USER="${DB_USER:-itflow}"
    APP_NAME="${APP_NAME:-ITFlow}"
    BASE_URL="${BASE_URL:-http://localhost}"
    HTTPS_ONLY="${HTTPS_ONLY:-FALSE}"
    REPO_BRANCH="${REPO_BRANCH:-master}"
    ENABLE_SETUP="${ENABLE_SETUP:-1}"
    
    # Generate installation ID if not provided
    generate_installation_id
    
    # Convert HTTPS_ONLY to boolean
    if [ "$HTTPS_ONLY" = "true" ] || [ "$HTTPS_ONLY" = "1" ]; then
        HTTPS_ONLY_VALUE="TRUE"
    else
        HTTPS_ONLY_VALUE="FALSE"
    fi
    
    # Create config directory if it doesn't exist
    mkdir -p "$CONFIG_DIR"
    
    # Generate config.php
    cat > "$CONFIG_FILE" <<EOF
<?php

/**
 * ITFlow Configuration File
 * Auto-generated by Docker on $(date)
 * Do not edit manually - use environment variables instead
 */

// Database Configuration
\$dbhost = '$DB_HOST';
\$dbusername = '$DB_USER';
\$dbpassword = '$DB_PASSWORD';
\$database = '$DB_NAME';

// Establish database connection
\$mysqli = mysqli_connect(\$dbhost, \$dbusername, \$dbpassword, \$database);

if (!\$mysqli) {
    die('Database Connection Failed: ' . mysqli_connect_error());
}

// Set character set to UTF-8
mysqli_set_charset(\$mysqli, 'utf8mb4');

// Application Configuration
\$config_app_name = '$APP_NAME';
\$config_base_url = '$BASE_URL';
\$config_https_only = $HTTPS_ONLY_VALUE;

// Repository branch for updates
\$repo_branch = '$REPO_BRANCH';

// Unique installation identifier
\$installation_id = '$INSTALLATION_ID';

// Setup configuration
\$config_enable_setup = $ENABLE_SETUP;

// Timezone
if (getenv('TZ')) {
    date_default_timezone_set(getenv('TZ'));
}

EOF
    
    # Set proper permissions
    chown www-data:www-data "$CONFIG_FILE"
    chmod 640 "$CONFIG_FILE"
    
    # Also save to config directory for persistence
    cp "$CONFIG_FILE" "$CONFIG_DIR/config.php" 2>/dev/null || true
    
    echo "config.php generated successfully!"
}

# Main execution
echo "=========================================="
echo "ITFlow Docker Container Starting"
echo "=========================================="

# Wait for database to be ready
wait_for_db

# Check if we need to initialize the database
if ! check_database_initialized; then
    initialize_database
fi

# Check if config.php already exists in persistent storage
if [ -f "$CONFIG_DIR/config.php" ] && [ "$ENABLE_SETUP" != "1" ]; then
    echo "Using existing config.php from persistent storage"
    cp "$CONFIG_DIR/config.php" "$CONFIG_FILE"
    chown www-data:www-data "$CONFIG_FILE"
    chmod 640 "$CONFIG_FILE"
else
    # Generate new config.php
    generate_config
fi

# Ensure upload directories exist with proper permissions
echo "Setting up upload directories..."
mkdir -p /var/www/html/uploads/tickets
mkdir -p /var/www/html/uploads/clients
chown -R www-data:www-data /var/www/html/uploads
chmod -R 775 /var/www/html/uploads

# Display configuration summary
echo "=========================================="
echo "Configuration Summary:"
echo "=========================================="
echo "Database Host: $DB_HOST:${DB_PORT:-3306}"
echo "Database Name: $DB_NAME"
echo "Database User: $DB_USER"
echo "App Name: $APP_NAME"
echo "Base URL: $BASE_URL"
echo "HTTPS Only: $HTTPS_ONLY"
echo "Setup Enabled: $ENABLE_SETUP"
echo "Timezone: ${TZ:-UTC}"
echo "=========================================="

# Execute the main command
echo "Starting application..."
exec "$@"
